repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: sync-requirements
        name: sync requirements.txt
        entry: uv export --no-hashes --no-dev --no-emit-project -o scripts/requirements.txt
        language: system
        files: ^(pyproject\.toml|uv\.lock)$
        pass_filenames: false
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]
      - id: codespell
        name: codespell
        entry: uv run codespell
        language: system
        types: [text]
      - id: mypy
        name: mypy
        entry: uv run mypy bot
        language: system
        types: [python]
        pass_filenames: false
#      - id: pytest
#        name: pytest
#        language: system
#        types: [python]
#        entry: uv run pytest -v
#        pass_filenames: false
#        always_run: true
